apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: fredapp
  labels:
    app: test
    type: new-app
spec:
  replicas: 4
  template:
    metadata:
      labels:
        tier:  frontend

    spec:
      containers:

       - image: busybox
         name: fredapp


  selector:
    matchLabels:
      tier: frontend
