apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: fredapp
  labels:
    app: test
    type: new-app
spec:
  replicas: 4
  template:
    metadata:
      tier: frontend
    spec:
      containers:
        -

          
        image: busybox


  selector:
    matchLabels:
      tier: frontend
